version: '3.4'

services:
  practiceproject.postgresql:
    image: postgres:14.1

  practiceproject.api:
    image: ${DOCKER_REGISTRY-}practiceprojectapi
    build:
      context: .
      dockerfile: Systems/Api/PracticeProject.Api/Dockerfile
